<!-- UserNotificationBanner.vue -->
<template>
  <div v-if="activeNotifications.length > 0" class="notification-banner-container">
    <!-- Notification Banner -->
    <div 
      v-for="notification in activeNotifications" 
      :key="notification.id"
      class="notification-banner"
      :class="getBannerClass(notification.priority)"
    >
      <div class="notification-content">
        <div class="flex items-start justify-between">
          <div class="flex items-center space-x-3 flex-1">
            <div class="notification-icon">
              <v-icon :color="getIconColor(notification.priority)" size="24">
                {{ getNotificationIcon(notification.priority) }}
              </v-icon>
            </div>
            <div class="notification-text flex-1">
              <h4 class="notification-title">{{ notification.title }}</h4>
              <p class="notification-message">{{ notification.message }}</p>
              
              <!-- แสดงตำแหน่งถ้ามี -->
              <div v-if="notification.location" class="notification-location">
                <v-icon size="16" class="mr-1">mdi-map-marker</v-icon>
                <span>{{ notification.location }}</span>
              </div>
              
              <!-- แสดงคำแนะนำถ้ามี -->
              <div v-if="notification.recommendations" class="notification-recommendations">
                <v-icon size="16" class="mr-1">mdi-lightbulb-outline</v-icon>
                <span class="font-semibold">คำแนะนำ:</span>
                <ul class="ml-4 mt-1 text-sm">
                  <li v-for="(rec, index) in notification.recommendations.split('\n')" :key="index">
                    • {{ rec }}
                  </li>
                </ul>
              </div>
              
              <div class="notification-meta">
                <span class="notification-time">{{ formatTime(notification.created_at) }}</span>
                <span class="notification-type">{{ getTypeLabel(notification.type) }}</span>
                <span v-if="notification.autoGenerated" class="notification-auto">
                  <v-icon size="12" class="mr-1">mdi-robot</v-icon>
                  อัตโนมัติ
                </span>
              </div>
            </div>
          </div>
          <button 
            @click="dismissNotification(notification.id)"
            class="notification-dismiss"
            title="ปิดการแจ้งเตือน"
          >
            <v-icon size="20">mdi-close</v-icon>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue'
import api from '@/plugins/axios'

export default {
  name: 'UserNotificationBanner',
  setup() {
    const activeNotifications = ref([])
    const refreshInterval = ref(null)
    
    // ฟังก์ชันโหลดการแจ้งเตือน
    const loadNotifications = async () => {
      try {
        // เรียก weather alerts endpoint สำหรับแจ้งเตือนภัยพิบัติ
        const weatherResponse = await api.get('/api/notifications/weather-alerts')
        
        // เรียก active notifications endpoint สำหรับแจ้งเตือนปกติ
        const activeResponse = await api.get('/api/notifications/active')
        
        let allNotifications = []
        
        // รวมข้อมูลจาก weather alerts
        if (weatherResponse.data.success) {
          allNotifications = allNotifications.concat(weatherResponse.data.data)
        }
        
        // รวมข้อมูลจาก active notifications
        if (activeResponse.data.success) {
          allNotifications = allNotifications.concat(activeResponse.data.data)
        }
        
        // กรองเฉพาะการแจ้งเตือนที่ยังไม่ได้ dismiss
        const dismissedIds = JSON.parse(localStorage.getItem('dismissedNotifications') || '[]')
        
        // ลบรายการที่ซ้ำกัน (ใช้ ID เป็นเกณฑ์)
        const uniqueNotifications = allNotifications.filter((notification, index, self) =>
          index === self.findIndex(n => n.id === notification.id)
        )
        
        // กรองเฉพาะที่ยังไม่ได้ dismiss
        activeNotifications.value = uniqueNotifications.filter(notification => 
          !dismissedIds.includes(notification.id)
        )
        
        // เรียงลำดับตามความสำคัญและเวลา
        activeNotifications.value.sort((a, b) => {
          const priorityOrder = { 'Critical': 4, 'High': 3, 'Medium': 2, 'Low': 1 }
          const aPriority = priorityOrder[a.priority] || 1
          const bPriority = priorityOrder[b.priority] || 1
          
          if (aPriority !== bPriority) {
            return bPriority - aPriority // ความสำคัญสูงก่อน
          }
          
          return new Date(b.created_at) - new Date(a.created_at) // ใหม่ก่อน
        })
        
        // แสดงแค่ 3 แจ้งเตือนแรก
        activeNotifications.value = activeNotifications.value.slice(0, 3)
        
      } catch (error) {
        console.error('Error loading notifications:', error)
      }
    }
    
    // ฟังก์ชันปิดการแจ้งเตือน
    const dismissNotification = (notificationId) => {
      // ลบจาก UI
      activeNotifications.value = activeNotifications.value.filter(n => n.id !== notificationId)
      
      // บันทึกลง localStorage
      const dismissedIds = JSON.parse(localStorage.getItem('dismissedNotifications') || '[]')
      dismissedIds.push(notificationId)
      localStorage.setItem('dismissedNotifications', JSON.stringify(dismissedIds))
    }
    
    // ฟังก์ชันจัดรูปแบบเวลา
    const formatTime = (datetime) => {
      if (!datetime) return ''
      const date = new Date(datetime)
      return date.toLocaleString('th-TH', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    }
    
    // ฟังก์ชันแสดงป้ายกำกับประเภท
    const getTypeLabel = (type) => {
      const labels = {
        'weather': 'อากาศ',
        'rain': 'ฝน',
        'storm': 'พายุ',
        'flood': 'น้ำท่วม',
        'drought': 'แล้ง',
        'emergency': 'ฉุกเฉิน',
        'system': 'ระบบ',
        'manual': 'ทั่วไป'
      }
      return labels[type.toLowerCase()] || type
    }
    
    // ฟังก์ชันแสดงไอคอน
    const getNotificationIcon = (priority) => {
      const icons = {
        'critical': 'mdi-alert-circle',
        'high': 'mdi-alert',
        'medium': 'mdi-information',
        'low': 'mdi-bell'
      }
      return icons[priority.toLowerCase()] || 'mdi-bell'
    }
    
    // ฟังก์ชันสีไอคอน
    const getIconColor = (priority) => {
      const colors = {
        'critical': 'red',
        'high': 'orange',
        'medium': 'blue',
        'low': 'green'
      }
      return colors[priority.toLowerCase()] || 'blue'
    }
    
    // ฟังก์ชันคลาส CSS
    const getBannerClass = (priority) => {
      const classes = {
        'critical': 'notification-critical',
        'high': 'notification-high',
        'medium': 'notification-medium',
        'low': 'notification-low'
      }
      return classes[priority.toLowerCase()] || 'notification-medium'
    }
    
    // Lifecycle
    onMounted(() => {
      loadNotifications()
      // รีเฟรชทุก 30 วินาที
      refreshInterval.value = setInterval(loadNotifications, 30000)
    })
    
    onUnmounted(() => {
      if (refreshInterval.value) {
        clearInterval(refreshInterval.value)
      }
    })
    
    return {
      activeNotifications,
      dismissNotification,
      formatTime,
      getTypeLabel,
      getNotificationIcon,
      getIconColor,
      getBannerClass
    }
  }
}
</script>

<style scoped>
.notification-banner-container {
  position: fixed;
  top: 70px;
  right: 20px;
  z-index: 1000;
  max-width: 400px;
  width: 100%;
}

.notification-banner {
  margin-bottom: 10px;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  animation: slideIn 0.3s ease-out;
}

@keyframes slideIn {
  from {
    transform: translateX(100%);
    opacity: 0;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
}

.notification-content {
  padding: 16px;
}

.notification-icon {
  flex-shrink: 0;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.2);
}

.notification-text {
  flex: 1;
}

.notification-title {
  font-size: 16px;
  font-weight: 600;
  margin: 0 0 4px 0;
  color: white;
}

.notification-message {
  font-size: 14px;
  margin: 0 0 8px 0;
  color: rgba(255, 255, 255, 0.9);
  line-height: 1.4;
}

.notification-location {
  display: flex;
  align-items: center;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.8);
  margin-bottom: 6px;
}

.notification-recommendations {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 6px;
  padding: 8px;
  margin: 8px 0;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.9);
}

.notification-recommendations ul {
  list-style: none;
  padding: 0;
}

.notification-recommendations li {
  margin: 2px 0;
  line-height: 1.3;
}

.notification-meta {
  display: flex;
  gap: 12px;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.7);
  align-items: center;
}

.notification-auto {
  display: flex;
  align-items: center;
  background: rgba(255, 255, 255, 0.2);
  padding: 2px 6px;
  border-radius: 10px;
  font-size: 10px;
}

.notification-dismiss {
  background: none;
  border: none;
  color: rgba(255, 255, 255, 0.8);
  cursor: pointer;
  padding: 4px;
  border-radius: 50%;
  transition: all 0.2s;
}

.notification-dismiss:hover {
  background: rgba(255, 255, 255, 0.2);
  color: white;
}

/* Priority Colors */
.notification-critical {
  background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%);
  border-left: 4px solid #fca5a5;
}

.notification-high {
  background: linear-gradient(135deg, #ea580c 0%, #c2410c 100%);
  border-left: 4px solid #fed7aa;
}

.notification-medium {
  background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%);
  border-left: 4px solid #93c5fd;
}

.notification-low {
  background: linear-gradient(135deg, #059669 0%, #047857 100%);
  border-left: 4px solid #86efac;
}

/* Responsive */
@media (max-width: 640px) {
  .notification-banner-container {
    top: 60px;
    right: 10px;
    left: 10px;
    max-width: none;
  }
  
  .notification-content {
    padding: 12px;
  }
  
  .notification-title {
    font-size: 14px;
  }
  
  .notification-message {
    font-size: 13px;
  }
}
</style>
